### PR TITLE
core: Add robots.txt

### PR DESCRIPTION
**Pull request by Koli14**
Note that, i don't really have understanding, about what I did, I just replicated all the lines containing favicon, and changed it to robots.txt...

### CODE REVIEW

**Review by luisherranz — COMMENTED** [review]
Code-wise it looks good to me.

@Koli14 could you please help us testing it out?

I think you should be able to do so using your repo as the builder

```json
{
  "builds": [
    {
      "src": "package.json",
      "use": "https://github.com/Koli14/now-builder"
    }
  ]
}
```

**Comment by Koli14** [comment]
I'm not sure what I need to do. I tried two things: 
- Modified the now.json in the [mars-example](https://github.com/frontity/frontity/blob/dev/examples/mars-theme-example/now.json) project, but then I get this error:
```
Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .vercelignore):
- {"src":"package.json","use":"@frontity/now"}
```
- Created a fresh frontity project with `npx frontity create`, created a now.json file, like [this](https://github.com/frontity/now-builder#before-deploying), and modifed as you suggested.
Then I get: `Error! Build failed`:

```
13:59:36.992  Retrieving list of deployment files...
13:59:37.164  Downloading 24 deployment files...
13:59:39.436  Installing build runtime...
13:59:41.825  Build runtime installed: 2388.764ms
13:59:42.108  Error: Cannot find module '/vercel/4c23e98f/.build-utils/.builder/node_modules/@frontity/now/dist/index.js'. Please verify that the package.json has a valid "main" entry
13:59:42.108      at tryPackage (internal/modules/cjs/loader.js:297:19)
13:59:42.108      at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
13:59:42.108      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
13:59:42.108      at Function.Module._load (internal/modules/cjs/loader.js:686:27)
13:59:42.108      at Module.require (internal/modules/cjs/loader.js:848:19)
13:59:42.108      at require (internal/modules/cjs/helpers.js:74:18)
13:59:42.108      at requireBuilder (/var/task/sandbox-worker.js:20225:14)
13:59:42.108      at installToolsStep2 (/var/task/sandbox-worker.js:20329:15)
13:59:42.108      at mainSub (/var/task/sandbox-worker.js:20123:33)
13:59:42.108      at async main (/var/task/sandbox-worker.js:20023:5) {
13:59:42.108    code: 'MODULE_NOT_FOUND',
13:59:42.108    path: '/vercel/4c23e98f/.build-utils/.builder/node_modules/@frontity/now/package.json',
13:59:42.108    requestPath: '/vercel/4c23e98f/.build-utils/.builder/node_modules/@frontity/now'
13:59:42.108  }
13:59:44.165  Done with "package.json"
```

**Comment by luisherranz** [comment]
Hey sorry, my fault. To test it out with GitHub repositories we need to push the `dist` folder, which is ignored by default.

I have tested it myself and added a conditional, so if the `robots.txt` file doesn't exist we go back to the default one.

Everything is working now 🙂

- Build without `robots.txt` file: https://now-test-di527zwgn.now.sh/robots.txt
- Build with `robots.txt` file: https://now-test-6byw6mb6d.now.sh/robots.txt

**Review by luisherranz — APPROVED** [review]
Thanks @Koli14 !! 🎉 🎉

**Comment by luisherranz** [comment]
I have published the new version in `"@frontity/now"` (1.1.0).

@Koli14 could you please confirm that it is working?

**Comment by Koli14** [comment]
> @Koli14 could you please confirm that it is working?

Yes, I tried it with an example mars-project, and it's working with both a robots.txt file and without. :) Thanks!

**Comment by luisherranz** [comment]
Awesome! Thanks to you @Koli14 🙂

**Pull request merged**
